# Generated by Django 5.0 on 2023-12-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="user_name",
            new_name="username",
        ),
    ]
